const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');

const channelPartnerSchema = new mongoose.Schema({
  name: {
    type: String,
    required: [true, 'Name is required'],
    trim: true,
    maxlength: [50, 'Name cannot exceed 50 characters']
  },
  phoneNumber: {
    type: String,
    required: [true, 'Phone number is required'],
    unique: true,
    trim: true,
    set: (v) => v.replace(/\D/g, ''), // Remove all non-digits before saving/validating
    match: [/^[0-9\s]{10,}$/, 'Please enter a valid 10-digit phone number']
  },
  partnerId: {
    type: String,
    trim: true,
    unique: true,
    sparse: true, // Allows multiple null values but enforces uniqueness for non-null values
    maxlength: [50, 'Partner ID cannot exceed 50 characters']
  },
  email: {
    type: String,
    trim: true,
    lowercase: true,
    match: [/^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$/, 'Please enter a valid email']
  },
  role: {
    type: String,
    enum: ['channel-partner'],
    default: 'channel-partner'
  },
  dateOfBirth: {
    type: Date
  },
  gender: {
    type: String,
    enum: ['male', 'female', 'other', 'prefer-not-to-say'],
    trim: true
  },
  joiningDate: {
    type: Date
  },
  document: {
    public_id: String,
    secure_url: String,
    originalName: String,
    original_filename: String,
    format: String,
    size: Number,
    bytes: Number,
    width: Number,
    height: Number,
    resource_type: String
  },
  isActive: {
    type: Boolean,
    default: true
  },
  lastLogin: {
    type: Date
  },
  loginAttempts: {
    type: Number,
    default: 0
  },
  lockUntil: {
    type: Date
  },
  // OTP related fields
  otp: {
    type: String,
    select: false // Don't include OTP in queries by default
  },
  otpExpires: {
    type: Date,
    select: false
  },
  otpAttempts: {
    type: Number,
    default: 0
  },
  otpLockUntil: {
    type: Date
  },
  // Channel Partner specific fields
  companyName: {
    type: String,
    trim: true,
    maxlength: [100, 'Company name cannot exceed 100 characters']
  },
  address: {
    street: String,
    city: String,
    state: String,
    country: String,
    zipCode: String
  },
  // Channel Partner preferences
  preferences: {
    notifications: {
      email: { type: Boolean, default: true },
      sms: { type: Boolean, default: true },
      push: { type: Boolean, default: true }
    },
    language: { type: String, default: 'en' },
    timezone: { type: String, default: 'Asia/Kolkata' }
  },
  // Total revenue generated by this channel partner
  totalRevenue: {
    type: Number,
    default: 0,
    min: 0
  },
  // Last activity (for tracking active channel partners)
  lastActivity: {
    type: Date,
    default: Date.now
  },
  // Sales Team Lead Assignment
  salesTeamLeadId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Sales',
    default: null
  },
  salesTeamLeadName: {
    type: String,
    trim: true,
    default: null
  },
  teamLeadAssignedDate: {
    type: Date,
    default: null
  },
  // FCM Tokens for push notifications
  fcmTokens: {
    type: [String],
    default: []
  },
  fcmTokenMobile: {
    type: [String],
    default: []
  }
}, {
  timestamps: true
});

// Index for better performance
// Note: phoneNumber index is created automatically by unique: true, so we don't need explicit index
channelPartnerSchema.index({ email: 1 });
channelPartnerSchema.index({ isActive: 1 });
channelPartnerSchema.index({ partnerId: 1 });

// Virtual for account lock status
channelPartnerSchema.virtual('isLocked').get(function () {
  return !!(this.lockUntil && this.lockUntil > Date.now());
});

// Virtual for OTP lock status
channelPartnerSchema.virtual('isOtpLocked').get(function () {
  return !!(this.otpLockUntil && this.otpLockUntil > Date.now());
});

// Virtual for OTP validity
channelPartnerSchema.virtual('isOtpValid').get(function () {
  return !!(this.otp && this.otpExpires && this.otpExpires > Date.now());
});

// Generate OTP
channelPartnerSchema.methods.generateOTP = function () {
  const otp = Math.floor(100000 + Math.random() * 900000).toString(); // 6-digit OTP
  this.otp = otp;
  this.otpExpires = Date.now() + 5 * 60 * 1000; // 5 minutes
  this.otpAttempts = 0;
  this.otpLockUntil = undefined;
  return otp;
};

// Verify OTP
channelPartnerSchema.methods.verifyOTP = function (candidateOTP) {
  if (!this.otp) {
    return false;
  }

  if (this.otpExpires && this.otpExpires < Date.now()) {
    return false;
  }

  return this.otp === candidateOTP;
};

// Increment OTP attempts
channelPartnerSchema.methods.incOtpAttempts = function () {
  // If we have a previous OTP lock that has expired, restart at 1
  if (this.otpLockUntil && this.otpLockUntil < Date.now()) {
    return this.updateOne({
      $unset: { otpLockUntil: 1 },
      $set: { otpAttempts: 1 }
    });
  }

  const updates = { $inc: { otpAttempts: 1 } };

  // Lock OTP after 3 failed attempts for 15 minutes
  if (this.otpAttempts + 1 >= 3 && !this.isOtpLocked) {
    updates.$set = { otpLockUntil: Date.now() + 15 * 60 * 1000 }; // 15 minutes
  }

  return this.updateOne(updates);
};

// Clear OTP
channelPartnerSchema.methods.clearOTP = function () {
  this.otp = undefined;
  this.otpExpires = undefined;
  this.otpAttempts = 0;
  this.otpLockUntil = undefined;
  return this.save();
};

// Increment login attempts
channelPartnerSchema.methods.incLoginAttempts = function () {
  // If we have a previous lock that has expired, restart at 1
  if (this.lockUntil && this.lockUntil < Date.now()) {
    return this.updateOne({
      $unset: { lockUntil: 1 },
      $set: { loginAttempts: 1 }
    });
  }

  const updates = { $inc: { loginAttempts: 1 } };

  // Lock account after 5 failed attempts for 2 hours
  if (this.loginAttempts + 1 >= 5 && !this.isLocked) {
    updates.$set = { lockUntil: Date.now() + 2 * 60 * 60 * 1000 }; // 2 hours
  }

  return this.updateOne(updates);
};

// Reset login attempts
channelPartnerSchema.methods.resetLoginAttempts = function () {
  return this.updateOne({
    $unset: { loginAttempts: 1, lockUntil: 1 },
    $set: { lastLogin: new Date() }
  });
};

// Sign JWT and return
channelPartnerSchema.methods.getSignedJwtToken = function () {
  return jwt.sign({ id: this._id, role: 'channel-partner' }, process.env.JWT_SECRET, {
    expiresIn: process.env.JWT_EXPIRE
  });
};

// Method to update total revenue
channelPartnerSchema.methods.updateTotalRevenue = function (amount) {
  this.totalRevenue += amount;
  this.lastActivity = new Date();
  return this.save();
};

// Remove sensitive data from JSON output
channelPartnerSchema.methods.toJSON = function () {
  const channelPartner = this.toObject();
  delete channelPartner.otp;
  delete channelPartner.otpExpires;
  delete channelPartner.otpAttempts;
  delete channelPartner.otpLockUntil;
  delete channelPartner.loginAttempts;
  delete channelPartner.lockUntil;
  return channelPartner;
};

module.exports = mongoose.model('ChannelPartner', channelPartnerSchema);
